name: Build and Publish to Nexus

on:
  # Manually triggered workflow using the "Run workflow" button
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest

   #set up the build enviroment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build with Maven
        run: mvn -B package -DskipTests
        
      - name: Set settings.xml
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
              "id": "mks-repo",
              "username": "${{ secrets.MAVEN_USERNAME }}",
              "password": "${{ secrets.MAVEN_TOKEN }}"
            },
            {
              "id": "mks-repo-snapshots",
              "username": "${{ secrets.MAVEN_USERNAME }}",
              "password": "${{ secrets.MAVEN_TOKEN }}"
            }]

      - name: Publish
        run: mvn --batch-mode clean deploy -DskipTests
